### ISSUE TITLE
Release on Maven Central?

### ISSUE THREAD

**Issue by dgelessus** [SpencerPark/jupyter-jvm-basekernel#11]
Are there any plans to put release versions of the basekernel on Maven Central? I'm asking because I'm planning to make a stable(-ish) release of my kernel soon, and I would prefer to have my dependencies be release versions rather than snapshots, so I know that they won't change after I make a release.

**Comment by SpencerPark** [comment]
Hi @dgelessus, that's great to hear! I think the kernel is at a fairly stable point right now and the bugs have stopped popping up.  I've started the process of publishing a release build that should be synced to maven central. I'm not sure how long the process takes but I can get it started (the first one might require some manual checks from the good folks over at sonatype). I believe it is just waiting on some automated requirements checks and a confirmation and then should be synced up to maven central under the same coordinates and the initial version `2.2.2`.

I'll close this when I confirm it's up there but you may also check out https://issues.sonatype.org/browse/OSSRH-37889 if you are interested.

**Comment by dgelessus** [comment]
@SpencerPark It's up [on Maven Central](https://search.maven.org/artifact/io.github.spencerpark/jupyter-jvm-basekernel/2.2.2/jar) now, and everything seems to be working fine. Thank you!

Yep, I would agree that the basekernel seems fairly stable now, I haven't encountered any more bugs :) Thank you again for fixing the issues that came up previously!

**Comment by SpencerPark** [comment]
Ahh yes it it! This is exciting, my first lib on maven central :)

I would also like to say a huge thank you to you as well for raising them, someone taking interest and the time to put up with bugs was extremely motivating and was a great contribution to the project.
