### ISSUE TITLE
How control Out cell color

### ISSUE THREAD

**Issue by pditommaso** [SpencerPark/jupyter-jvm-basekernel#16]
When the a cell output renders a basic string text using via DisplayData the cell placeholder is displayed in red color (see image)

![cellout](https://user-images.githubusercontent.com/816968/48967031-315f3700-efdb-11e8-93b5-32c037995841.png)

From the user perspective this can be interpreted as a possible cell execution error. What does it control the color of the cell placeholder when rendering the cell output?

**Comment by SpencerPark** [comment]
Hi @pditommaso, that nextflow in the top right is looking great! :) 

The notebook ui here is from https://github.com/jupyter/notebook. If you really want to change it you could provide a [kernel.js](https://carreau.gitbooks.io/jupyter-book/content/kerneljs.html) modifies the css.

I will say though that a kernel should not change these things as kernels should be front-end agnostic. Changing a style like this should be an end user decision in which case there are many options for changing jupyter's theme including the `custom.css` route.

**Comment by pditommaso** [comment]
OK, I was not realising that is the default colour  for cell output, I was thinking I was missing something in the usage of `DisplayData`. if so that's good.

> that nextflow in the top right is looking great! 

It does ;)
