### ISSUE TITLE
How retrieve current notebook file name

### ISSUE THREAD

**Issue by pditommaso** [SpencerPark/jupyter-jvm-basekernel#17]
How to retrieve from the kernel the current notebook file name (and path)?

**Comment by SpencerPark** [comment]
Hi @pditommaso, this is not something you can do with the protocol. The kernel is meant to be frontend agnostic and as such has no idea what notebook it is running in (or even if it is running in a notebook). The kernel could also potentially be on a different machine that the notebook entirely!

You may be able to set up a comm and notebook extension if absolutely necessary but I don't believe it should be. What is the end goal you are trying to achieve with this information?

Also note that the current working directory of the kernel is usually set to the notebook that triggered jupyter to spawn the kernel but you shouldn't rely on this behavior.

**Comment by pditommaso** [comment]
Thanks for your comment and sorry for the late reply. The notebook name it would have been useful in in the kernel integration I'm exploring but I understand your points about the protocol abstraction.
