### ISSUE TITLE
What is the purpose of DisplayData.EMPTY?

### ISSUE THREAD

**Issue by dgelessus** [SpencerPark/jupyter-jvm-basekernel#8]
In the `DisplayData` class, there is the `EMPTY` constant, which is a `DisplayData` with no content. When would it be useful to return that from `eval`? At first I thought `EMPTY` would be used for cells with no result, but that is done by returning `null`, not `EMPTY`. In the notebook, an `EMPTY` result looks just like `EMPTY_STRING`, so I'm a bit confused what the difference is.

**Comment by SpencerPark** [comment]
Visually I don't think any front-ends make handle things differently but internally `EMPTY` has no representations of any data where as `EMPTY_STRING` has a `text/plain` representation that is empty.

There is really no case for returning `EMPTY` from `eval`, `EMPTY_STRING` is the proper way if you would like a published but empty output as it has a `text/plain` representation which many jupyter related tools assume is available on anything displayed. 

`EMPTY` is used in the `inspect_reply` to save a couple bytes as the output is never used when `found` is false.

It might be a bit misleading. Do you think it's worth removing? It's very scarcely used internally.

**Comment by dgelessus** [comment]
Ah, that makes sense, I didn't know it was used internally. The [spec for `inspect_reply`](https://jupyter-client.readthedocs.io/en/stable/messaging.html#introspection) even says "data can be empty if nothing is found", so that is a normal and supported use case for an empty result.

The reason why I was confused is that the [spec for `execute_result`](https://jupyter-client.readthedocs.io/en/stable/messaging.html#id6) says that "a plain text representation should always be provided in the `text/plain` mime-type". I didn't know that there were other cases where the data dict can be empty, so I was wondering why there was a constant for something that the spec recommends against.
